name: LLMart Test Runner

on:
  push:
    branches: [ "adarsh/gh-runner" ] # TODO: Change this to main after testing
  pull_request:
    branches: [ "adarsh/gh-runner" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv, huggingface_hub and login
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        pip install huggingface_hub
        echo -e "${HUGGINGFACE_TOKEN}\nY\n" | huggingface-cli login

    - name: Run README commands
      run: make

    - name: Run all examples and cleanup
      run: make -C examples/